const polaroids = [
  ["Jessie Buckley and Paul Mescal", "Hamnet", 2],
  ["Rose Byrne", "If I Had Legs I’d Kick You", 1],
  ["Teyana Taylor", "One Battle After Another", 4],
  ["Stellan Skarsgård", "Sentimental Value", 1],
  ["Owen Cooper", "Adolescence", 1],
  ["Noah Wyle", "The Pitt", 2],
  ["Amy Poehler", "Good Hang With Amy Poehler", 1],
  ["Wagner Moura", "The Secret Agent", 1],
  ["Rhea Seehorn", "Pluribus", 2],
  ["Paul Thomas Anderson", "One Battle After Another", 1],
  ["Chase Infiniti", "One Battle After Another", 4],
  ["Ashley Walters", "Adolescence", 1],
  ["Seth Rogen", "The Studio", 2],
  ["Peter Huyck", "The Studio", 1],
  ["Evan Goldberg and Chase Sui Wonders", "The Studio", 2],
  ["Stephen Graham", "Adolescence", 1],
  ["Joe Alwyn", "Hamnet", 1],
]; // ГЛАВНЫЙ МАССИВ